// Generated by CoffeeScript 1.12.5
(function() {
  var _Class, _Status, _Tedy, _forTest, _statusCall, i, item, len, twos, type;

  _Class = false;

  _Status = "Boby";

  _statusCall = function(x) {
    var y;
    y = x;
    if (y >= 1 && y <= 5) {
      alert('ilk okul : ' + y);
    }
    if (y >= 6 && y <= 8) {
      alert('Orta Okul : ' + y);
    }
    if (y >= 9 && y <= 12) {
      return alert('Lise : ' + y);
    }
  };

  _forTest = function(x) {
    var i, results;
    results = [];
    for (x = i = 1; i <= 7; x = ++i) {
      results.push(alert(x));
    }
    return results;
  };

  _Tedy = {
    baby: _forTest(0),
    kind: alet("Kind"),
    young: alert("Young"),
    funcs: function(x) {
      return alert("FUNCTION_TEST");
    },
    obs: {
      a: alert("a"),
      b: alert("b"),
      c: alert("c")
    }
  };

  item = ["Rice", "Boby"];

  for (i = 0, len = type.length; i < len; i++) {
    item = type[i];
    if (item === "Rice") {
      item + "s";
    }
  }

  type = (function() {
    var j, len1, results;
    results = [];
    for (j = 0, len1 = type.length; j < len1; j++) {
      item = type[j];
      if (item !== "Rice") {
        results.push(item + "s");
      }
    }
    return results;
  })();

  twos = (function() {
    var j, len1, results;
    results = [];
    for (j = 0, len1 = tyoe.length; j < len1; j++) {
      item = tyoe[j];
      if (item !== "Rice") {
        results.push(item);
      }
    }
    return results;
  })();

}).call(this);

//# sourceMappingURL=run.js.map
